#!/bin/bash
function RunSway(){
	disabledGPU=`cat ~/.config/waydroid-runner//.config/waydroid-runner/disable-gpu`
	isDisbledGPU=0
	if [[ $disabledGPU == "1" ]] || [[ ! -f ~/.config/waydroid-runner/disable-gpu ]]; then
		isDisbledGPU=1
	fi
	lspci | grep -i nvidia
	if [[ $? == 0 ]] && [[ $isDisbledGPU == 1 ]]; then
		nohup sway --unsupported-gpu > /dev/null 2>&1 &
	else
		nohup sway > /dev/null 2>&1 &
	fi
}
function RunWeston(){
	nohup weston > /dev/null 2>&1 &
}
if [[ $WAYLAND_DISPLAY == "" ]]; then
	# 自动识别 WAYLAND（以在 X11 通过 sway 运行 Waydroid）
	if [[ -e /run/user/$UID/wayland-0 ]]; then
		export WAYLAND_DISPLAY=wayland-0
	else
		ls /run/user/$UID/wayland-* > /dev/null 2>&1
		if [[ $? != 0 ]]; then
			if [[ `whoami` == root ]]; then
				echo root 用户不支持自动启动 Sway 或 Weston 以设置 WAYLAND_DISPLAY
			else
				# 读取设置
				setting=`cat ~/.config/waydroid-runner/x11-set`
				isEnabledSway=0
				if [[ $setting == "sway" ]] || [[ ! -f ~/.config/waydroid-runner/x11-set ]]; then
					isEnabledSway=1
				fi
				which sway  > /dev/null 2>&1
				if [[ $? == 0 ]] && [[ $isEnabledSway == 1 ]]; then
					RunSway
				else
					which weston  > /dev/null 2>&1
					if [[ $? == 0 ]]; then
						RunWeston
					fi
				fi
				sleep 2
				if [[ -e /run/user/$UID/wayland-0 ]]; then
					export WAYLAND_DISPLAY=wayland-0
				else
					ls /run/user/$UID/wayland-* > /dev/null 2>&1
					if [[ $? == 0 ]]; then
						export WAYLAND_DISPLAY=`ls /run/user/$UID/wayland-* | awk '{print $NF}' | head -n1`
						export WAYLAND_DISPLAY=`basename $WAYLAND_DISPLAY`
					else
						echo 无法设置默认 WAYLAND_DISPLAY，请手动设置
					fi
				fi
			fi
		else
			export WAYLAND_DISPLAY=`ls /run/user/$UID/wayland-* | awk '{print $NF}' | head -n1`
			export WAYLAND_DISPLAY=`basename $WAYLAND_DISPLAY`
		fi
	fi
fi
echo 当前设置 WAYLAND_DISPLAY：$WAYLAND_DISPLAY
waydroid-session "$@"

