#!/bin/bash
ln -s /opt/apps/spark-waydroid-runner/files/waydroid-runner                   /usr/bin/waydroid-runner
ln -s /opt/apps/spark-waydroid-runner/files/AutoShell/main.py                /usr/bin/waydroid-runner-auto-install-bash
# 刷新图标缓存
# 因为 Ubuntu 的问题，省略
gtk-update-icon-cache /usr/share/icons/bloom > /dev/null | true
# 向服务器返回安装数加1（不显示内容且忽略错误）
python3 /opt/apps/spark-waydroid-runner/files/Download.py 1.0.0 > /dev/null | true